version: "3"
services:
  notifications-frontend:
    build: ./notifications-frontend
    container_name: notifications-frontend
    restart: always
    environment:
      NODE_ENV: local
    ports:
      - "3000:3000"
      - 9080:9080

  gila-notifications:
    build: ./gilaNotifications
    container_name: "gila-notifications"
    restart: always
    environment:
      NODE_ENV: "local"
      APP_PORT: 3001
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "admin"
      DB_NAME: "gilaNotifications"
    ports:
      - "3001:3001"
      - 9229:9229
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: "gilaNotifications"
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /data/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
    volumes:
        - ./data/init.sql:/data/init.sql
    security_opt:
      - seccomp:unconfined